# -*- coding: utf-8 -*-
"""task 2 EDA Superstore

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MtuJgWltHCOO2LCM2YHKzFcb_Yp19UGL
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Cleaned_SampleSuperstore.csv")

df.head()

df.info()

df.describe()

plt.figure(figsize=(8,5))

plt.hist(df['Sales'], bins=30)

plt.title("Sales Distribution")
plt.xlabel("Sales")
plt.ylabel("Frequency")

plt.show()

category_sales = df.groupby('Category')['Sales'].sum()

category_sales.plot(kind='bar')

plt.title("Sales by Category")
plt.ylabel("Sales")

plt.show()

region_profit = df.groupby('Region')['Profit'].sum()

region_profit.plot(kind='bar')

plt.title("Profit by Region")
plt.ylabel("Profit")

plt.show()

sns.scatterplot(x='Region', y='Profit', data=df)

plt.title("Region vs Profit")

plt.show()

correlation_matrix = df.corr(numeric_only=True)

sns.heatmap(correlation_matrix, annot=True)

plt.title("Correlation Heatmap")

plt.show()

